// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/api/grpc/wallet.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *WalletResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WalletResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *WalletResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WalletResponse) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type ListWalletsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletsRequest) Reset() {
	*x = ListWalletsRequest{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletsRequest) ProtoMessage() {}

func (x *ListWalletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletsRequest.ProtoReflect.Descriptor instead.
func (*ListWalletsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ListWalletsRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ListWalletsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*WalletResponse      `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletsResponse) Reset() {
	*x = ListWalletsResponse{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletsResponse) ProtoMessage() {}

func (x *ListWalletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletsResponse.ProtoReflect.Descriptor instead.
func (*ListWalletsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ListWalletsResponse) GetWallets() []*WalletResponse {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type SignMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageRequest) Reset() {
	*x = SignMessageRequest{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageRequest) ProtoMessage() {}

func (x *SignMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageRequest.ProtoReflect.Descriptor instead.
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *SignMessageRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SignMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SignMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageResponse) Reset() {
	*x = SignMessageResponse{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageResponse) ProtoMessage() {}

func (x *SignMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageResponse.ProtoReflect.Descriptor instead.
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *SignMessageResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignMessageResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type SignTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *SignTransactionRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SignTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SignTransactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction string                 `protobuf:"bytes,1,opt,name=signed_transaction,json=signedTransaction,proto3" json:"signed_transaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *SignTransactionResponse) GetSignedTransaction() string {
	if x != nil {
		return x.SignedTransaction
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         string                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *Balance) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Balance) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice      string                 `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Nonce         uint64                 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *Transaction) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Transaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Transaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_internal_api_grpc_wallet_proto protoreflect.FileDescriptor

const file_internal_api_grpc_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/api/grpc/wallet.proto\x12\twallet.v1\"/\n" +
	"\x13CreateWalletRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\"\x9b\x01\n" +
	"\x0eWalletResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\".\n" +
	"\x12ListWalletsRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\"J\n" +
	"\x13ListWalletsResponse\x123\n" +
	"\awallets\x18\x01 \x03(\v2\x19.wallet.v1.WalletResponseR\awallets\"K\n" +
	"\x12SignMessageRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"R\n" +
	"\x13SignMessageResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"o\n" +
	"\x16SignTransactionRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x128\n" +
	"\vtransaction\x18\x02 \x01(\v2\x16.wallet.v1.TransactionR\vtransaction\"H\n" +
	"\x17SignTransactionResponse\x12-\n" +
	"\x12signed_transaction\x18\x01 \x01(\tR\x11signedTransaction\"0\n" +
	"\x11GetBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"B\n" +
	"\x12GetBalanceResponse\x12,\n" +
	"\abalance\x18\x01 \x01(\v2\x12.wallet.v1.BalanceR\abalance\"7\n" +
	"\aBalance\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\xc6\x01\n" +
	"\vTransaction\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x1b\n" +
	"\tgas_limit\x18\x06 \x01(\x04R\bgasLimit\x12\x1b\n" +
	"\tgas_price\x18\a \x01(\tR\bgasPrice\x12\x14\n" +
	"\x05nonce\x18\b \x01(\x04R\x05nonce2\xe0\x03\n" +
	"\rWalletService\x12I\n" +
	"\fCreateWallet\x12\x1e.wallet.v1.CreateWalletRequest\x1a\x19.wallet.v1.WalletResponse\x12C\n" +
	"\tGetWallet\x12\x1b.wallet.v1.GetWalletRequest\x1a\x19.wallet.v1.WalletResponse\x12L\n" +
	"\vListWallets\x12\x1d.wallet.v1.ListWalletsRequest\x1a\x1e.wallet.v1.ListWalletsResponse\x12L\n" +
	"\vSignMessage\x12\x1d.wallet.v1.SignMessageRequest\x1a\x1e.wallet.v1.SignMessageResponse\x12X\n" +
	"\x0fSignTransaction\x12!.wallet.v1.SignTransactionRequest\x1a\".wallet.v1.SignTransactionResponse\x12I\n" +
	"\n" +
	"GetBalance\x12\x1c.wallet.v1.GetBalanceRequest\x1a\x1d.wallet.v1.GetBalanceResponseB9Z7github.com/rickyreddygari/walletsdk/internal/api/grpcpbb\x06proto3"

var (
	file_internal_api_grpc_wallet_proto_rawDescOnce sync.Once
	file_internal_api_grpc_wallet_proto_rawDescData []byte
)

func file_internal_api_grpc_wallet_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_wallet_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_wallet_proto_rawDesc), len(file_internal_api_grpc_wallet_proto_rawDesc)))
	})
	return file_internal_api_grpc_wallet_proto_rawDescData
}

var file_internal_api_grpc_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_api_grpc_wallet_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),     // 0: wallet.v1.CreateWalletRequest
	(*WalletResponse)(nil),          // 1: wallet.v1.WalletResponse
	(*GetWalletRequest)(nil),        // 2: wallet.v1.GetWalletRequest
	(*ListWalletsRequest)(nil),      // 3: wallet.v1.ListWalletsRequest
	(*ListWalletsResponse)(nil),     // 4: wallet.v1.ListWalletsResponse
	(*SignMessageRequest)(nil),      // 5: wallet.v1.SignMessageRequest
	(*SignMessageResponse)(nil),     // 6: wallet.v1.SignMessageResponse
	(*SignTransactionRequest)(nil),  // 7: wallet.v1.SignTransactionRequest
	(*SignTransactionResponse)(nil), // 8: wallet.v1.SignTransactionResponse
	(*GetBalanceRequest)(nil),       // 9: wallet.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),      // 10: wallet.v1.GetBalanceResponse
	(*Balance)(nil),                 // 11: wallet.v1.Balance
	(*Transaction)(nil),             // 12: wallet.v1.Transaction
}
var file_internal_api_grpc_wallet_proto_depIdxs = []int32{
	1,  // 0: wallet.v1.ListWalletsResponse.wallets:type_name -> wallet.v1.WalletResponse
	12, // 1: wallet.v1.SignTransactionRequest.transaction:type_name -> wallet.v1.Transaction
	11, // 2: wallet.v1.GetBalanceResponse.balance:type_name -> wallet.v1.Balance
	0,  // 3: wallet.v1.WalletService.CreateWallet:input_type -> wallet.v1.CreateWalletRequest
	2,  // 4: wallet.v1.WalletService.GetWallet:input_type -> wallet.v1.GetWalletRequest
	3,  // 5: wallet.v1.WalletService.ListWallets:input_type -> wallet.v1.ListWalletsRequest
	5,  // 6: wallet.v1.WalletService.SignMessage:input_type -> wallet.v1.SignMessageRequest
	7,  // 7: wallet.v1.WalletService.SignTransaction:input_type -> wallet.v1.SignTransactionRequest
	9,  // 8: wallet.v1.WalletService.GetBalance:input_type -> wallet.v1.GetBalanceRequest
	1,  // 9: wallet.v1.WalletService.CreateWallet:output_type -> wallet.v1.WalletResponse
	1,  // 10: wallet.v1.WalletService.GetWallet:output_type -> wallet.v1.WalletResponse
	4,  // 11: wallet.v1.WalletService.ListWallets:output_type -> wallet.v1.ListWalletsResponse
	6,  // 12: wallet.v1.WalletService.SignMessage:output_type -> wallet.v1.SignMessageResponse
	8,  // 13: wallet.v1.WalletService.SignTransaction:output_type -> wallet.v1.SignTransactionResponse
	10, // 14: wallet.v1.WalletService.GetBalance:output_type -> wallet.v1.GetBalanceResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_wallet_proto_init() }
func file_internal_api_grpc_wallet_proto_init() {
	if File_internal_api_grpc_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_wallet_proto_rawDesc), len(file_internal_api_grpc_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_wallet_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_wallet_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_wallet_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_wallet_proto = out.File
	file_internal_api_grpc_wallet_proto_goTypes = nil
	file_internal_api_grpc_wallet_proto_depIdxs = nil
}
